version: "3.9"

services:
  db:
    image: mysql
    container_name: db
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/entries:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 25s

  nodejs:
    image: nodejs
    container_name: nodejs
    build: ./nodejs
    networks:
      - node-network
    depends_on:
      db:
        condition: service_healthy

  proxy:
    image: proxy
    build: ./nginx
    container_name: proxy
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - nodejs

networks:
  node-network:
    driver: bridge
