version: "3.9"

services:
  db:
    image: mysql
    container_name: db
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - node-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  nodejs:
    container_name: nodejs
    build: ./nodejs
    networks:
      - node-network

  proxy:
    build: ./nginx
    container_name: proxy
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - db

networks:
  node-network:
    driver: bridge
